### ISSUE TITLE
Configuring incomplete

### ISSUE THREAD

**Issue by arifrohim** [deroproject/dero#1]
-- Configuring incomplete, errors occurred!
See also "/root/dero/build/release/CMakeFiles/CMakeOutput.log".
See also "/root/dero/build/release/CMakeFiles/CMakeError.log".
make: *** [release-all] Error 1

**Comment by CaptainDero** [comment]
Can you attach above two log files.

**Comment by CaptainDero** [comment]
Insufficient details.
