### ISSUE TITLE
Copyright notice on difficulty algorithm

### ISSUE THREAD

**Issue by thaerkh** [deroproject/dero#6]
Hello,

Thanks for using Masari's difficulty algorithm implementation. However, proper copyright retention needs to be in place, with something like a "Portions Copyright (c) 2017, The Masari Project" on the Readme and a "Copyright (c) 2017, The Masari Project" on the difficulty.cpp file.

Thanks in advance for your cooperation,
Thaer

**Comment by CaptainDero** [comment]
Thanks for bringing to our notice and your work. 
Though masari is already mentioned, will add proper copyright https://github.com/deroproject/dero/blob/master/src/cryptonote_basic/difficulty.cpp#L134

Just give us few hrs.
Thanks.

**Comment by bobbieltd** [comment]
@CaptainDero Could you please switch back to old algo ? I’m really annoyed with this copyright issue. I agree for difficulty.cpp copyright notice. But demand for Readme copyright is too much. You can just remove those codes and put back old codes.

**Comment by thaerkh** [comment]
@bobbieltd this issue ticket is regarding BSD license's requirement for retaining a copyright notice with redistributed code (as well as a copy of the license). In open source software, it's common/polite to have all corresponding licenses listed out in documentation (i.e. Readme), however as far as the BSD license is concerned it isn't required outside the code in question, and that documentation portion is under the discretion of @CaptainDero.

**Comment by CaptainDero** [comment]
Documentation Updated.
